name = ""
level = 1
race = ""
class = ""
proficiencies = []

[ability_scores]
Strength = 10
Dexterity = 10
Constitution = 10
Wisdom = 10
Intelligence = 10
Charisma = 10

[inventory]
Weapons = []
Armor = []
Items = []

[spells]
Level = [[], [], [], [], [], [], [], [], [], []]
